version: "3.8"

services:
  # apple-watch-series-6:
  #   build: ./kyc-contract
  #   mem_limit: 1g
  #   cpus: "2.0"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: "2.0"
  #       reservations:
  #         memory: 512M
  #         cpus: "1.0"
  #   depends_on:
  #     - go-jedi

  # apple-watch-se:
  #   build: ./kyc-contract
  #   mem_limit: 1g
  #   cpus: "2.0"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: "2.0"
  #       reservations:
  #         memory: 512M
  #         cpus: "1.0"
  #   depends_on:
  #     - go-jedi
  # apple-watch-series-5:
  #   build: ./kyc-contract
  #   mem_limit: 1g
  #   cpus: "2.0"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: "2.0"
  #       reservations:
  #         memory: 512M
  #         cpus: "1.0"
  #   depends_on:
  #     - go-jedi

  # apple-watch-series-4:
  #   build: ./kyc-contract
  #   mem_limit: 1g
  #   cpus: "2.0"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1G
  #         cpus: "2.0"
  #       reservations:
  #         memory: 512M
  #         cpus: "1.0"
  #   depends_on:
  #     - go-jedi

  # raspberry-pi:
  #   build: ./kyc-contract
  #   mem_limit: 2g
  #   cpus: "2"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 2G
  #         cpus: "2"
  #       reservations:
  #         memory: 1G
  #         cpus: "1"
  #   depends_on:
  #     - go-jedi

  # fitbit:
  #   build: ./kyc-contract
  #   mem_limit: 256m
  #   cpus: "0.5"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 256M
  #         cpus: "0.5"
  #       reservations:
  #         memory: 128M
  #         cpus: "0.25"
  #   depends_on:
  #     - go-jedi

  # kyc-contract:
  #   build: ./kyc-contract
  #   depends_on:
  #     - go-jedi

  go-jedi:
    build: ./go-jedi
    volumes:
      - ./go-jedi:/app
      - ./go-jedi/go:/go
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "2"

  # smart-band:
  #   build: ./kyc-contract
  #   mem_limit: 128m
  #   cpus: "0.2"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #         cpus: "0.2"
  #       reservations:
  #         memory: 64M
  #         cpus: "0.1"
  #   depends_on:
  #     - go-jedi

  # low-power-sensor:
  #   build: ./kyc-contract
  #   mem_limit: 64m
  #   cpus: "0.1"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 64M
  #         cpus: "0.1"
  #       reservations:
  #         memory: 32M
  #         cpus: "0.05"
  #   depends_on:
  #     - go-jedi

  # ble-beacon:
  #   build: ./kyc-contract
  #   mem_limit: 32m
  #   cpus: "0.05"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 32M
  #         cpus: "0.05"
  #       reservations:
  #         memory: 16M
  #         cpus: "0.02"
  #   depends_on:
  #     - go-jedi
